[package]
name = "snowflake"
version = "0.1.0"
authors = ["zhenghuarong <zhenghuarong@yy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.5.2"